# base
title: 글그리 개발 블로그
email: eastroot1590@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  개발 공부를 하면서 배우고 익힌 내용을 기록하여 공유한다.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://eastroot1590.github.io # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: 이동근
  email: eastroot1590@gmail.com
  
# minima
minima:
  social_links:
    github: eastroot1590

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
